// By Vanadiry

var list = [
  { name: "恋塚 小夢", bday: "0303", origin: "こみっくがーるず" },
  { name: "萌田 薫子", bday: "0401", origin: "こみっくがーるず" },
  { name: "勝木 翼", bday: "0504", origin: "こみっくがーるず" },
  { name: "花園 莉々香", bday: "0514", origin: "こみっくがーるず" },
  { name: "怖浦 すず", bday: "0726", origin: "こみっくがーるず" },
  { name: "色川 美姫", bday: "0906", origin: "こみっくがーるず" },
  { name: "色川 琉姫", bday: "1224", origin: "こみっくがーるず" },
  { name: "編沢 まゆ", bday: "0710", origin: "こみっくがーるず" },
  { name: "虹野 美晴", bday: "1113", origin: "こみっくがーるず" },
  { name: "直枝 理樹", bday: "0117", origin: "クドわふたー" },
  { name: "能美 クドリャフカ", bday: "0612", origin: "クドわふたー" },
  { name: "井ノ上 たきな", bday: "0802", origin: "リコリス・リコイル" },
  { name: "錦木 千束", bday: "0923", origin: "リコリス・リコイル" },
  { name: "クルミ", bday: "1216", origin: "リコリス・リコイル" },
  { name: "中原 ミズキ", bday: "0605", origin: "リコリス・リコイル" },
  { name: "ミカ", bday: "0713", origin: "リコリス・リコイル" },
  { name: "春川 フキ", bday: "0924", origin: "リコリス・リコイル" },
  { name: "万年 大会", bday: "0109", origin: "スロウスタート" },
  { name: "一之瀬 花名", bday: "0406", origin: "スロウスタート" },
  { name: "百地 たまて", bday: "0523", origin: "スロウスタート" },
  { name: "十倉 栄依子", bday: "0620", origin: "スロウスタート" },
  { name: "千石 冠", bday: "1030", origin: "スロウスタート" },
  { name: "京塚 志温", bday: "1106", origin: "スロウスタート" },
  { name: "十倉 光希", bday: "0227", origin: "スロウスタート" },
  { name: "榎並 清瀬", bday: "0310", origin: "スロウスタート" },
  { name: "億 果実", bday: "0930", origin: "スロウスタート" },
  { name: "兆野 綴", bday: "0615", origin: "スロウスタート" },
  { name: "溝端 創", bday: "0319", origin: "スロウスタート" },
  { name: "雪見 小梅", bday: "0201", origin: "うらら迷路帖" },
  { name: "巽 绀", bday: "0315", origin: "うらら迷路帖" },
  { name: "千矢", bday: "0402", origin: "うらら迷路帖" },
  { name: "二条臣", bday: "0609", origin: "うらら迷路帖" },
  { name: "棗 ニナ", bday: "0625", origin: "うらら迷路帖" },
  { name: "色井 佐久", bday: "0801", origin: "うらら迷路帖" },
  { name: "棗 ノノ", bday: "1216", origin: "うらら迷路帖" },
  { name: "和泉 紗霧", bday: "1210", origin: "エロマンガ先生" },
  { name: "霧島 翔子", bday: "1111", origin: "バカとテストと召喚獣" },
  { name: "工藤 愛子", bday: "0211", origin: "バカとテストと召喚獣" },
  { name: "木下 優子", bday: "1006", origin: "バカとテストと召喚獣" },
  { name: "吉井 明久", bday: "0306", origin: "バカとテストと召喚獣" },
  { name: "姫路 瑞希", bday: "1221", origin: "バカとテストと召喚獣" },
  { name: "島田 美波", bday: "1010", origin: "バカとテストと召喚獣" },
  { name: "坂本 雄二", bday: "0609", origin: "バカとテストと召喚獣" },
  { name: "木下 秀吉", bday: "1006", origin: "バカとテストと召喚獣" },
  { name: "土屋 康太", bday: "0412", origin: "バカとテストと召喚獣" },
  { name: "緒山 まひろ", bday: "0306", origin: "お兄ちゃんはおしまい！" },
  { name: "緒山 みはり", bday: "0422", origin: "お兄ちゃんはおしまい！" },
  { name: "桜花 朝日", bday: "0505", origin: "お兄ちゃんはおしまい！" },
  { name: "室崎 美夜", bday: "0618", origin: "お兄ちゃんはおしまい！" },
  { name: "穂月 かえで", bday: "0912", origin: "お兄ちゃんはおしまい！" },
  { name: "穂月 もみじ", bday: "1020", origin: "お兄ちゃんはおしまい！" },
  { name: "天川  なゆた", bday: "1123", origin: "お兄ちゃんはおしまい！" },
  { name: "愛城 恋太郎", bday: "0501", origin: "君のことが大大大大大好きな100人の彼女" },
  { name: "花園 羽香里", bday: "0622", origin: "君のことが大大大大大好きな100人の彼女" },
  { name: "院田 唐音", bday: "0909", origin: "君のことが大大大大大好きな100人の彼女" },
  { name: "好本 静", bday: "1101", origin: "君のことが大大大大大好きな100人の彼女" },
  { name: "栄逢 凪乃", bday: "0314", origin: "君のことが大大大大大好きな100人の彼女" },
  { name: "薬膳 楠莉", bday: "0418", origin: "君のことが大大大大大好きな100人の彼女" },
  { name: "花園 羽々里", bday: "0512", origin: "君のことが大大大大大好きな100人の彼女" },
  { name: "原賀 胡桃", bday: "0903", origin: "君のことが大大大大大好きな100人の彼女" },
  { name: "須藤 育", bday: "0109", origin: "君のことが大大大大大好きな100人の彼女" },
  { name: "美杉 美々美", bday: "0303", origin: "君のことが大大大大大好きな100人の彼女" },
  { name: "華暮 愛愛", bday: "1010", origin: "君のことが大大大大大好きな100人の彼女" },
  { name: "銘戸 芽衣", bday: "0510", origin: "君のことが大大大大大好きな100人の彼女" },
  { name: "柊 うてな", bday: "1114", origin: "魔法少女にあこがれて" },
  { name: "阿良河 キウィ", bday: "0706", origin: "魔法少女にあこがれて" },
  { name: "杜乃 こりす", bday: "0208", origin: "魔法少女にあこがれて" },
  { name: "阿古屋 真珠", bday: "0408", origin: "魔法少女にあこがれて" },
  { name: "姉母 ネモ", bday: "0623", origin: "魔法少女にあこがれて" },
  { name: "田中 みち子", bday: "0127", origin: "魔法少女にあこがれて" },
  { name: "花菱 はるか", bday: "0430", origin: "魔法少女にあこがれて" },
  { name: "水神 小夜", bday: "0901", origin: "魔法少女にあこがれて" },
  { name: "天川 薰子", bday: "0817", origin: "魔法少女にあこがれて" },
  { name: "桃森 百花", bday: "0928", origin: "魔法少女にあこがれて" },
  { name: "多田 蘭朶", bday: "1211", origin: "魔法少女にあこがれて" },
  { name: "桜木 ひな子", bday: "0430", origin: "ひなこのーと" },
  { name: "中島 ゆあ", bday: "0510", origin: "ひなこのーと" },
  { name: "夏川 くいな", bday: "0707", origin: "ひなこのーと" },
  { name: "黒柳 ルリ子", bday: "0807", origin: "ひなこのーと" },
  { name: "萩野 千秋", bday: "1001", origin: "ひなこのーと" },
  { name: "柊 真雪", bday: "1224", origin: "ひなこのーと" },
  { name: "苗木 誠", bday: "0205", origin: "ダンガンロンパ" },
  { name: "舞園 さやか", bday: "0707", origin: "ダンガンロンパ" },
  { name: "霧切 響子", bday: "1006", origin: "ダンガンロンパ" },
  { name: "不二咲 千尋", bday: "0314", origin: "ダンガンロンパ" },
  { name: "桑田 怜恩", bday: "0103", origin: "ダンガンロンパ" },
  { name: "十神 白夜", bday: "0505", origin: "ダンガンロンパ" },
  { name: "山田 一二三", bday: "1231", origin: "ダンガンロンパ" },
  { name: "大和田 紋土", bday: "0609", origin: "ダンガンロンパ" },
  { name: "腐川 冬子", bday: "0303", origin: "ダンガンロンパ" },
  { name: "安広 多恵子", bday: "1123", origin: "ダンガンロンパ" },
  { name: "朝日奈 葵", bday: "0424", origin: "ダンガンロンパ" },
  { name: "石丸 清多夏", bday: "0831", origin: "ダンガンロンパ" },
  { name: "大神 さくら", bday: "0913", origin: "ダンガンロンパ" },
  { name: "葉隱 康比呂", bday: "0725", origin: "ダンガンロンパ" },
  { name: "江ノ島 盾子", bday: "1224", origin: "ダンガンロンパ" },
  { name: "桜ノ宮 苺香", bday: "0404", origin: "ブレンド・S" },
  { name: "天野 美雨", bday: "0609", origin: "ブレンド・S" },
  { name: "神崎 ひでり", bday: "0710", origin: "ブレンド・S" },
  { name: "日向 夏帆", bday: "0812", origin: "ブレンド・S" },
  { name: "星川 麻冬", bday: "1223", origin: "ブレンド・S" },
  { name: "秋月 紅葉", bday: "1128", origin: "ブレンド・S" },
  { name: "ディーノ", bday: "0505", origin: "ブレンド・S" },
  { name: "里中 チエ", bday: "0101", origin: "大家さんは思春期！" },
  { name: "本場 切絵", bday: "0315", origin: "干物妹！うまるちゃん" },
  { name: "土間 タイヘイ", bday: "0602", origin: "干物妹！うまるちゃん" },
  { name: "土間 うまる", bday: "0926", origin: "干物妹！うまるちゃん" },
  { name: "海老名 菜々", bday: "1019", origin: "干物妹！うまるちゃん" },
  { name: "橘・シルフィンフォード", bday: "1224", origin: "干物妹！うまるちゃん" },
  { name: "橘・アレックス", bday: "1224", origin: "干物妹！うまるちゃん" },
  { name: "本場 猛", bday: "0805", origin: "干物妹！うまるちゃん" },
  { name: "後藤 ひとり", bday: "0221", origin: "ぼっち・ざ・ろっく！" },
  { name: "喜多 郁代", bday: "0421", origin: "ぼっち・ざ・ろっく！" },
  { name: "伊地知 虹夏", bday: "0529", origin: "ぼっち・ざ・ろっく！" },
  { name: "大槻 ヨヨコ", bday: "0602", origin: "ぼっち・ざ・ろっく！" },
  { name: "山田 リョウ", bday: "0918", origin: "ぼっち・ざ・ろっく！" },
  { name: "廣井 きくり", bday: "0928", origin: "ぼっち・ざ・ろっく！" },
  { name: "伊地知 星歌", bday: "1224", origin: "ぼっち・ざ・ろっく！" },
  { name: "前原 圭一", bday: "0413", origin: "ひぐらしのなく頃に" },
  { name: "竜宮 レナ", bday: "0728", origin: "ひぐらしのなく頃に" },
  { name: "園崎 魅音", bday: "0710", origin: "ひぐらしのなく頃に" },
  { name: "北条 沙都子", bday: "0624", origin: "ひぐらしのなく頃に" },
  { name: "古手 梨花", bday: "0821", origin: "ひぐらしのなく頃に" },
  { name: "園崎 詩音", bday: "0710", origin: "ひぐらしのなく頃に" },
  { name: "羽入", bday: "0801", origin: "ひぐらしのなく頃に" },
  { name: "知恵 留美子", bday: "0503", origin: "ひぐらしのなく頃に" },
  { name: "大石 蔵人", bday: "1115", origin: "ひぐらしのなく頃に" },
  { name: "富竹 ジロウ", bday: "0914", origin: "ひぐらしのなく頃に" },
  { name: "鷹野 三四", bday: "0620", origin: "ひぐらしのなく頃に" },
  { name: "入江 京介", bday: "1203", origin: "ひぐらしのなく頃に" },
  { name: "北条 铁平", bday: "0528", origin: "ひぐらしのなく頃に" },
  { name: "赤坂 衛", bday: "0803", origin: "ひぐらしのなく頃に" },
  { name: "北条 悟史", bday: "0616", origin: "ひぐらしのなく頃に" },
  { name: "葛西 辰由", bday: "1223", origin: "ひぐらしのなく頃に" },
  { name: "大宮 忍", bday: "0606", origin: "きんいろモザイク" },
  { name: "アリス・カータレット", bday: "0405", origin: "きんいろモザイク" },
  { name: "小路 綾", bday: "0915", origin: "きんいろモザイク" },
  { name: "猪熊 陽子", bday: "0820", origin: "きんいろモザイク" },
  { name: "九条 カレン", bday: "1201", origin: "きんいろモザイク" },
  { name: "松原 穂乃花", bday: "0113", origin: "きんいろモザイク" },
  { name: "日暮 香奈", bday: "0510", origin: "きんいろモザイク" },
  { name: "大宮 勇", bday: "0202", origin: "きんいろモザイク" },
  { name: "烏丸 さくら", bday: "1019", origin: "きんいろモザイク" },
  { name: "久世橋 朱里", bday: "0724", origin: "きんいろモザイク" },
  { name: "栗山 未来", bday: "0331", origin: "境界の彼方" },
  { name: "神原 秋人", bday: "1007", origin: "境界の彼方" },
  { name: "名瀬 美月", bday: "1101", origin: "境界の彼方" },
  { name: "名瀬 博臣", bday: "0721", origin: "境界の彼方" },
  { name: "新堂 愛", bday: "0825", origin: "境界の彼方" },
  { name: "新堂 彩華", bday: "0522", origin: "境界の彼方" },
  { name: "二ノ宮 雫", bday: "0618", origin: "境界の彼方" },
  { name: "伊波 桜", bday: "0429", origin: "境界の彼方" },
  { name: "藤真 弥勒", bday: "0108", origin: "境界の彼方" },
  { name: "名瀬 泉", bday: "0407", origin: "境界の彼方" },
  { name: "神原 弥生", bday: "0313", origin: "境界の彼方" },
  { name: "森野 真理", bday: "0219", origin: "恋する小惑星" },
  { name: "真中 あお", bday: "0525", origin: "恋する小惑星" },
  { name: "木ノ幡 みら", bday: "0613", origin: "恋する小惑星" },
  { name: "桜井 美景", bday: "0720", origin: "恋する小惑星" },
  { name: "猪瀬 舞", bday: "0912", origin: "恋する小惑星" },
  { name: "遠藤 幸", bday: "0810", origin: "恋する小惑星" },
  { name: "宇佐美 綾乃", bday: "0412", origin: "恋する小惑星" },
  { name: "桜井 千景", bday: "0510", origin: "恋する小惑星" },
  { name: "伊部 小百合", bday: "1111", origin: "恋する小惑星" },
  { name: "七海 悠", bday: "0102", origin: "恋する小惑星" },
  { name: "木ノ幡 みさ", bday: "1202", origin: "恋する小惑星" },
  { name: "鈴矢 芽", bday: "0314", origin: "恋する小惑星" },
  { name: "鈴矢 萌", bday: "1002", origin: "恋する小惑星" },
  { name: "宗像 草太", bday: "0224", origin: "すずめの戸締まり" },
  { name: "岩戸鈴芽", bday: "0524", origin: "すずめの戸締まり" },
  { name: "九頭竜 八一", bday: "0801", origin: "りゅうおうのおしごと！" },
  { name: "水越 澪", bday: "0824", origin: "りゅうおうのおしごと！" },
  { name: "空 銀子", bday: "0909", origin: "りゅうおうのおしごと！" },
  { name: "雛鶴 あい", bday: "1007", origin: "りゅうおうのおしごと！" },
  { name: "贞任 绫乃", bday: "1203", origin: "りゅうおうのおしごと！" },
  { name: "夜叉神 天衣", bday: "1210", origin: "りゅうおうのおしごと！" },
  { name: "清滝 桂香", bday: "1109", origin: "りゅうおうのおしごと！" },
  { name: "清滝 鋼介", bday: "1101", origin: "りゅうおうのおしごと！" },
  { name: "明日 花緒", bday: "0216", origin: "明日ちゃんのセーラー服" },
  { name: "木崎 江利花", bday: "0323", origin: "明日ちゃんのセーラー服" },
  { name: "明日 小路", bday: "0404", origin: "明日ちゃんのセーラー服" },
  { name: "平岩 蛍", bday: "1007", origin: "明日ちゃんのセーラー服" },
  { name: "兎原 透子", bday: "0219", origin: "明日ちゃんのセーラー服" },
  { name: "大熊 実", bday: "1124", origin: "明日ちゃんのセーラー服" },
  { name: "神黙 根子", bday: "0606", origin: "明日ちゃんのセーラー服" },
  { name: "古城 智乃", bday: "1003", origin: "明日ちゃんのセーラー服" },
  { name: "四条 璃生奈", bday: "0828", origin: "明日ちゃんのセーラー服" },
  { name: "龍守 逢", bday: "0808", origin: "明日ちゃんのセーラー服" },
  { name: "谷川 景", bday: "0627", origin: "明日ちゃんのセーラー服" },
  { name: "峠口 鮎美", bday: "0103", origin: "明日ちゃんのセーラー服" },
  { name: "戸鹿野 舞衣", bday: "0926", origin: "明日ちゃんのセーラー服" },
  { name: "苗代 靖子", bday: "0225", origin: "明日ちゃんのセーラー服" },
  { name: "水上 リリ", bday: "0514", origin: "明日ちゃんのセーラー服" },
  { name: "蛇森 生静", bday: "1111", origin: "明日ちゃんのセーラー服" },
  { name: "鷲尾 瞳", bday: "1030", origin: "明日ちゃんのセーラー服" },
  { name: "田村 頼", bday: "1224", origin: "明日ちゃんのセーラー服" },
  { name: "明日 ユワ", bday: "0820", origin: "明日ちゃんのセーラー服" },
  { name: "明日 サト", bday: "1221", origin: "明日ちゃんのセーラー服" },
  { name: "福元 幹", bday: "0120", origin: "明日ちゃんのセーラー服" },
  { name: "岡部 倫太郎", bday: "1214", origin: "Steins；Gate" },
  { name: "椎名 まゆり", bday: "0201", origin: "Steins；Gate" },
  { name: "橋田 至", bday: "0519", origin: "Steins；Gate" },
  { name: "牧瀬 紅莉栖", bday: "0725", origin: "Steins；Gate" },
  { name: "桐生 萌郁", bday: "0606", origin: "Steins；Gate" },
  { name: "漆原 るか", bday: "0830", origin: "Steins；Gate" },
  { name: "秋葉 留未穂", bday: "0403", origin: "Steins；Gate" },
  { name: "阿万音 鈴羽", bday: "0927", origin: "Steins；Gate" },
  { name: "比屋定 真帆", bday: "1102", origin: "Steins；Gate" },
  { name: "椎名 かがり", bday: "0707", origin: "Steins；Gate" },
  { name: "阿万音 由季", bday: "0531", origin: "Steins；Gate" },
  { name: "天王寺 裕吾", bday: "0312", origin: "Steins；Gate" },
  { name: "中瀨 克美", bday: "0114", origin: "Steins；Gate" },
  { name: "来嶋 かえで", bday: "1004", origin: "Steins；Gate" },
  { name: "アレクシス・レスキネン", bday: "0823", origin: "Steins；Gate" },
  { name: "ジュディ・レイエス", bday: "0613", origin: "Steins；Gate" },
  { name: "環 いろは", bday: "0822", origin: "マギアレコード 魔法少女まどか☆マギカ外伝" },
  { name: "朝霧 彩", bday: "0408", origin: "魔法少女サイト" },
  { name: "穴沢 虹海", bday: "0705", origin: "魔法少女サイト" },
  { name: "奴村 露乃", bday: "0409", origin: "魔法少女サイト" },
  { name: "雨谷 小雨", bday: "1106", origin: "魔法少女サイト" },
  { name: "水莲寺 清春", bday: "1112", origin: "魔法少女サイト" },
  { name: "潮井 梨ナ", bday: "1208", origin: "魔法少女サイト" },
  { name: "雫芽 纱理奈", bday: "0425", origin: "魔法少女サイト" },
  { name: "鹿目 まどか", bday: "1003", origin: "魔法少女まどか☆マギカ" },
  { name: "キキ", bday: "0202", origin: "魔女の宅急便" },
  { name: "一ノ瀬 双葉", bday: "0825", origin: "それが声優！" },
  { name: "萌咲 いちご", bday: "0505", origin: "それが声優！" },
  { name: "小花 鈴", bday: "0317", origin: "それが声優！" },
  { name: "立花 瀧", bday: "1201", origin: "君の名は。" },
  { name: "宮水 三葉", bday: "1201", origin: "君の名は。" },
  { name: "海凪 ひより", bday: "0104", origin: "スローループ" },
  { name: "吉永 恋", bday: "0630", origin: "スローループ" },
  { name: "海凪 小春", bday: "1115", origin: "スローループ" },
  { name: "福元 一花", bday: "0802", origin: "スローループ" },
  { name: "福元 二葉", bday: "0512", origin: "スローループ" },
  { name: "二宮 藍子", bday: "0922", origin: "スローループ" },
  { name: "青沼 ねいる", bday: "0427", origin: "ワンダーエッグ・プライオリティ" },
  { name: "沢木 桃恵", bday: "0330", origin: "ワンダーエッグ・プライオリティ" },
  { name: "川井 リカ", bday: "1018", origin: "ワンダーエッグ・プライオリティ" },
  { name: "大戸 アイ", bday: "0615", origin: "ワンダーエッグ・プライオリティ" },
  { name: "風衣葉 冬優", bday: "0124", origin: "ご注文はうさぎですか？" },
  { name: "天々座 理世", bday: "0214", origin: "ご注文はうさぎですか？" },
  { name: "保登 モカ", bday: "0313", origin: "ご注文はうさぎですか？" },
  { name: "保登 心愛", bday: "0410", origin: "ご注文はうさぎですか？" },
  { name: "桐間 紗路", bday: "0715", origin: "ご注文はうさぎですか？" },
  { name: "条河 麻耶", bday: "0808", origin: "ご注文はうさぎですか？" },
  { name: "宇治松 千夜", bday: "0919", origin: "ご注文はうさぎですか？" },
  { name: "青山 翠", bday: "1027", origin: "ご注文はうさぎですか？" },
  { name: "奈津 恵", bday: "1102", origin: "ご注文はうさぎですか？" },
  { name: "香風 智乃", bday: "1204", origin: "ご注文はうさぎですか？" },
  { name: "神沙 映月", bday: "0615", origin: "ご注文はうさぎですか？" },
  { name: "神沙 夏明", bday: "0615", origin: "ご注文はうさぎですか？" },
  { name: "狩手 結良", bday: "0112", origin: "ご注文はうさぎですか？" },
  { name: "真手 凛", bday: "0504", origin: "ご注文はうさぎですか？" },
  { name: "羽島 伊月", bday: "0606", origin: "妹さえいればいい。" },
  { name: "羽島 千尋", bday: "0906", origin: "妹さえいればいい。" },
  { name: "可児 那由多", bday: "0710", origin: "妹さえいればいい。" },
  { name: "白川 京", bday: "0429", origin: "妹さえいればいい。" },
  { name: "石田 将也", bday: "0208", origin: "聲の形" },
  { name: "西宮 硝子", bday: "0607", origin: "聲の形" },
  { name: "池谷 乃々", bday: "0201", origin: "ステラのまほう" },
  { name: "藤川 歌夜", bday: "0402", origin: "ステラのまほう" },
  { name: "飯野 水葉", bday: "0509", origin: "ステラのまほう" },
  { name: "関 あやめ", bday: "0723", origin: "ステラのまほう" },
  { name: "本田 珠輝", bday: "0828", origin: "ステラのまほう" },
  { name: "布田 裕美音", bday: "0914", origin: "ステラのまほう" },
  { name: "百武 照", bday: "1222", origin: "ステラのまほう" },
  { name: "村上 椎奈", bday: "1225", origin: "ステラのまほう" },
  { name: "天野 陽菜", bday: "0822", origin: "天気の子" },
  { name: "種村 小依", bday: "0220", origin: "私に天使が舞い降りた！" },
  { name: "小之森 夏音", bday: "0228", origin: "私に天使が舞い降りた！" },
  { name: "白咲 花", bday: "0307", origin: "私に天使が舞い降りた！" },
  { name: "星野 ひなた", bday: "0510", origin: "私に天使が舞い降りた！" },
  { name: "星野 みやこ", bday: "0909", origin: "私に天使が舞い降りた！" },
  { name: "姫坂 乃愛", bday: "1124", origin: "私に天使が舞い降りた！" },
  { name: "松本 香子", bday: "1016", origin: "私に天使が舞い降りた！" },
  { name: "松本 友奈", bday: "0507", origin: "私に天使が舞い降りた！" },
  { name: "星野 千鶴", bday: "0118", origin: "私に天使が舞い降りた！" },
  { name: "ノエル", bday: "1103", origin: "天体のメソッド" },
  { name: "高坂 桐乃", bday: "0408", origin: "俺の妹がこんなに可愛いわけがない" },
  { name: "五更 瑠璃", bday: "0420", origin: "俺の妹がこんなに可愛いわけがない" },
  { name: "新垣 あやせ", bday: "0502", origin: "俺の妹がこんなに可愛いわけがない" },
  { name: "田村 麻奈実", bday: "0504", origin: "俺の妹がこんなに可愛いわけがない" },
  { name: "斎藤 かえで", bday: "0116", origin: "ヤマノススメ" },
  { name: "雪村 あおい", bday: "0219", origin: "ヤマノススメ" },
  { name: "千手院 小春", bday: "0518", origin: "ヤマノススメ" },
  { name: "黒崎 ほのか", bday: "0625", origin: "ヤマノススメ" },
  { name: "青羽 ここな", bday: "0811", origin: "ヤマノススメ" },
  { name: "倉上 ひなた", bday: "1111", origin: "ヤマノススメ" },
  { name: "小野塚 ひかり", bday: "0229", origin: "ヤマノススメ" },
  { name: "笹原 ゆうか", bday: "0518", origin: "ヤマノススメ" },
  { name: "小林", bday: "0423", origin: "小林さんちのメイドラゴン" },
  { name: "才川 苗", bday: "0510", origin: "小林さんちのメイドラゴン" },
  { name: "才川 リコ", bday: "0821", origin: "小林さんちのメイドラゴン" },
  { name: "滝谷 真", bday: "0505", origin: "小林さんちのメイドラゴン" },
  { name: "真ヶ土 翔太", bday: "1222", origin: "小林さんちのメイドラゴン" },
  { name: "雷門 瞬", bday: "0409", origin: "星屑テレパス" },
  { name: "宝木 遥乃", bday: "1018", origin: "星屑テレパス" },
  { name: "小ノ星 海果", bday: "0122", origin: "星屑テレパス" },
  { name: "椎名", bday: "0217", origin: "幸腹グラフィティ" },
  { name: "町子 リョウ", bday: "0622", origin: "幸腹グラフィティ" },
  { name: "森野 きりん", bday: "1219", origin: "幸腹グラフィティ" },
  { name: "佐倉 慈", bday: "0310", origin: "がっこうぐらし！" },
  { name: "丈槍 由紀", bday: "0405", origin: "がっこうぐらし！" },
  { name: "恵飛須沢 胡桃", bday: "0807", origin: "がっこうぐらし！" },
  { name: "若狭 悠里", bday: "1011", origin: "がっこうぐらし！" },
  { name: "直樹 美紀", bday: "1210", origin: "がっこうぐらし！" },
  { name: "赤座 あかり", bday: "0724", origin: "ゆるゆり" },
  { name: "歳納 京子", bday: "0328", origin: "ゆるゆり" },
  { name: "船見 結衣", bday: "0422", origin: "ゆるゆり" },
  { name: "吉川 ちなつ", bday: "1106", origin: "ゆるゆり" },
  { name: "杉浦 綾乃", bday: "0120", origin: "ゆるゆり" },
  { name: "池田 千歳", bday: "0310", origin: "ゆるゆり" },
  { name: "大室 櫻子", bday: "0907", origin: "ゆるゆり" },
  { name: "古谷 向日葵", bday: "0616", origin: "ゆるゆり" },
  { name: "松本 りせ", bday: "0523", origin: "ゆるゆり" },
  { name: "西垣 奈々", bday: "0621", origin: "ゆるゆり" },
  { name: "池田 千鶴", bday: "0310", origin: "ゆるゆり" },
  { name: "船見 まり", bday: "0830", origin: "ゆるゆり" },
  { name: "古谷 楓", bday: "1030", origin: "ゆるゆり" },
  { name: "大室 撫子", bday: "0121", origin: "ゆるゆり" },
  { name: "大室 花子", bday: "0807", origin: "ゆるゆり" },
  { name: "吉川 ともこ", bday: "0216", origin: "ゆるゆり" },
  { name: "赤座 あかね", bday: "1213", origin: "ゆるゆり" },
  { name: "志摩 リン", bday: "1001", origin: "ゆるキャン△" },
  { name: "各務原 なでしこ", bday: "0304", origin: "ゆるキャン△" },
  { name: "犬山 あおい", bday: "0304", origin: "ゆるキャン△" },
  { name: "大垣 千明", bday: "0831", origin: "ゆるキャン△" },
  { name: "斉藤 恵那", bday: "0901", origin: "ゆるキャン△" },
  { name: "御庭 つみき", bday: "0111", origin: "あっちこっち" },
  { name: "戌井 榊", bday: "0414", origin: "あっちこっち" },
  { name: "春野 姫", bday: "0512", origin: "あっちこっち" },
  { name: "桜川 キクヱ", bday: "1204", origin: "あっちこっち" },
  { name: "片濑 真宵", bday: "0910", origin: "あっちこっち" },
  { name: "音無 伊御", bday: "1015", origin: "あっちこっち" },
  { name: "チョイ・モチマッヅィ", bday: "0303", origin: "たまこまーけっと" },
  { name: "朝霧 史織", bday: "0402", origin: "たまこまーけっと" },
  { name: "メチャ・モチマッヅィ", bday: "0406", origin: "たまこまーけっと" },
  { name: "北白川 あんこ", bday: "0504", origin: "たまこまーけっと" },
  { name: "牧野 かんな", bday: "0607", origin: "たまこまーけっと" },
  { name: "常盤 みどり", bday: "0819", origin: "たまこまーけっと" },
  { name: "大路 もち蔵", bday: "1010", origin: "たまこまーけっと" },
  { name: "北白川 たまこ", bday: "1231", origin: "たまこまーけっと" },
  { name: "春日野 悠", bday: "0205", origin: "ヨスガノソラ" },
  { name: "春日野 穹", bday: "0205", origin: "ヨスガノソラ" },
  { name: "倉永 梢", bday: "0601", origin: "ヨスガノソラ" },
  { name: "渚 一葉", bday: "0803", origin: "ヨスガノソラ" },
  { name: "天女目 瑛", bday: "0803", origin: "ヨスガノソラ" },
  { name: "伊福部 八寻", bday: "0110", origin: "ヨスガノソラ" },
  { name: "乃木坂 初佳", bday: "1223", origin: "ヨスガノソラ" },
  { name: "中里 亮平", bday: "0925", origin: "ヨスガノソラ" },
  { name: "依媛 奈緒", bday: "1007", origin: "ヨスガノソラ" },
  { name: "桐生 慧輝", bday: "1011", origin: "可愛ければ変態でも好きになってくれますか？" },
  { name: "桐生 瑞葉", bday: "0303", origin: "可愛ければ変態でも好きになってくれますか？" },
  { name: "雛月 加代", bday: "0302", origin: "僕だけがいない街" },
  { name: "藤沼 悟", bday: "0302", origin: "僕だけがいない街" },
  { name: "小鳥遊 十花", bday: "0215", origin: "中二病でも恋がしたい！" },
  { name: "小鳥遊 六花", bday: "0612", origin: "中二病でも恋がしたい！" },
  { name: "七宮 智音", bday: "0706", origin: "中二病でも恋がしたい！" },
  { name: "富樫 勇太", bday: "0707", origin: "中二病でも恋がしたい！" },
  { name: "凸守 早苗", bday: "0809", origin: "中二病でも恋がしたい！" },
  { name: "丹生谷 森夏", bday: "0830", origin: "中二病でも恋がしたい！" },
  { name: "五月七日 くみん", bday: "1014", origin: "中二病でも恋がしたい！" },
  { name: "一色 誠", bday: "1207", origin: "中二病でも恋がしたい！" },
  { name: "巫部 風鈴", bday: "1114", origin: "中二病でも恋がしたい！" },
  { name: "神前 美月", bday: "1221", origin: "最近、妹のようすがちょっとおかしいんだが。" },
];

var today = new Date();
var month = today.getMonth() + 1;
var day = today.getDate();
if (month < 10) {
  month = "0" + month;
}
if (day < 10) {
  day = "0" + day;
}
var date = month + day;

var result = [];
for (var i = 0; i < list.length; i++) {
  var item = list[i];
  if (item.bday == date) {
    result.push(item);
  }
}

if (result.length == 0) {
  document.getElementById("result").innerHTML = "今天没有角色生日...";
} else {
  var output = "";
  for (var j = 0; j < result.length; j++) {
    var role = result[j];
    output += role.name + " [" + role.origin + "]" + "<br>";
  }
  document.getElementById("result").innerHTML = output;
}