// By Vanadiry

var list = [
  { name: "恋冢小梦", bday: "0303", origin: "Comic Girls" },
  { name: "萌田薰子", bday: "0401", origin: "Comic Girls" },
  { name: "胜木翼", bday: "0504", origin: "Comic Girls" },
  { name: "花园莉莉香", bday: "0514", origin: "Comic Girls" },
  { name: "怖浦铃", bday: "0726", origin: "Comic Girls" },
  { name: "色川美姬", bday: "0906", origin: "Comic Girls" },
  { name: "色川琉姬", bday: "1224", origin: "Comic Girls" },
  { name: "直枝理树", bday: "0117", origin: "Kud Wafter" },
  { name: "能美库特莉亚芙卡", bday: "0612", origin: "Kud Wafter" },
  { name: "井之上泷奈", bday: "0802", origin: "Lycoris Recoil" },
  { name: "锦木千束", bday: "0923", origin: "Lycoris Recoil" },
  { name: "胡桃", bday: "1216", origin: "Lycoris Recoil" },
  { name: "万年大会", bday: "0109", origin: "Slow Start" },
  { name: "一之濑花名", bday: "0406", origin: "Slow Start" },
  { name: "百地玉手", bday: "0523", origin: "Slow Start" },
  { name: "十仓荣依子", bday: "0620", origin: "Slow Start" },
  { name: "千石冠", bday: "1030", origin: "Slow Start" },
  { name: "京冢志温", bday: "1106", origin: "Slow Start" },
  { name: "雪见小梅", bday: "0201", origin: "Urara迷路帖" },
  { name: "巽绀", bday: "0315", origin: "Urara迷路帖" },
  { name: "千矢", bday: "0402", origin: "Urara迷路帖" },
  { name: "二条臣", bday: "0609", origin: "Urara迷路帖" },
  { name: "枣妮娜", bday: "0625", origin: "Urara迷路帖" },
  { name: "色井佐久", bday: "0801", origin: "Urara迷路帖" },
  { name: "枣乃乃", bday: "1216", origin: "Urara迷路帖" },
  { name: "和泉纱雾", bday: "1210", origin: "埃罗芒阿老师" },
  { name: "雾岛翔子", bday: "1111", origin: "笨蛋、测验、召唤兽" },
  { name: "工藤爱子", bday: "0211", origin: "笨蛋、测验、召唤兽" },
  { name: "木下优子", bday: "1006", origin: "笨蛋、测验、召唤兽" },
  { name: "吉井明久", bday: "0306", origin: "笨蛋、测验、召唤兽" },
  { name: "姬路瑞希", bday: "1221", origin: "笨蛋、测验、召唤兽" },
  { name: "岛田美波", bday: "1010", origin: "笨蛋、测验、召唤兽" },
  { name: "坂本雄二", bday: "0609", origin: "笨蛋、测验、召唤兽" },
  { name: "木下秀吉", bday: "1006", origin: "笨蛋、测验、召唤兽" },
  { name: "土屋康太", bday: "0412", origin: "笨蛋、测验、召唤兽" },
  { name: "绪山真寻", bday: "0306", origin: "别当欧尼酱了！" },
  { name: "绪山美波里", bday: "0422", origin: "别当欧尼酱了！" },
  { name: "樱花朝日", bday: "0505", origin: "别当欧尼酱了！" },
  { name: "室崎美夜", bday: "0618", origin: "别当欧尼酱了！" },
  { name: "穗月枫", bday: "0912", origin: "别当欧尼酱了！" },
  { name: "穗月椛", bday: "1020", origin: "别当欧尼酱了！" },
  { name: "天川那由多", bday: "1123", origin: "别当欧尼酱了！" },
  { name: "爱城恋太郎", bday: "0501", origin: "超超超超超喜欢你的100个女朋友" },
  { name: "花园羽香里", bday: "0622", origin: "超超超超超喜欢你的100个女朋友" },
  { name: "院田唐音", bday: "0909", origin: "超超超超超喜欢你的100个女朋友" },
  { name: "好本静", bday: "1101", origin: "超超超超超喜欢你的100个女朋友" },
  { name: "荣逢凪乃", bday: "0314", origin: "超超超超超喜欢你的100个女朋友" },
  { name: "药膳楠莉", bday: "0418", origin: "超超超超超喜欢你的100个女朋友" },
  { name: "花园羽羽里", bday: "0512", origin: "超超超超超喜欢你的100个女朋友" },
  { name: "铭户芽衣", bday: "0510", origin: "超超超超超喜欢你的100个女朋友" },
  { name: "柊舞缇娜", bday: "1114", origin: "憧憬成为魔法少女" },
  { name: "阿良河基维", bday: "0706", origin: "憧憬成为魔法少女" },
  { name: "杜乃可莉丝", bday: "0208", origin: "憧憬成为魔法少女" },
  { name: "阿古屋真珠", bday: "0408", origin: "憧憬成为魔法少女" },
  { name: "姊母娞摩", bday: "0623", origin: "憧憬成为魔法少女" },
  { name: "田中满子", bday: "0127", origin: "憧憬成为魔法少女" },
  { name: "花菱春香", bday: "0430", origin: "憧憬成为魔法少女" },
  { name: "水神小夜", bday: "0901", origin: "憧憬成为魔法少女" },
  { name: "天川薰子", bday: "0817", origin: "憧憬成为魔法少女" },
  { name: "桃森百花", bday: "0928", origin: "憧憬成为魔法少女" },
  { name: "多田兰朵", bday: "1211", origin: "憧憬成为魔法少女" },
  { name: "樱木雏子", bday: "0430", origin: "雏子的笔记" },
  { name: "中岛优亚", bday: "0510", origin: "雏子的笔记" },
  { name: "夏川玖井菜", bday: "0707", origin: "雏子的笔记" },
  { name: "黑柳琉璃子", bday: "0807", origin: "雏子的笔记" },
  { name: "萩野千秋", bday: "1001", origin: "雏子的笔记" },
  { name: "柊真雪", bday: "1224", origin: "雏子的笔记" },
  { name: "苗木诚", bday: "0205", origin: "弹丸论破" },
  { name: "樱之宫莓香", bday: "0404", origin: "调教咖啡厅" },
  { name: "天野美雨", bday: "0609", origin: "调教咖啡厅" },
  { name: "神崎日照", bday: "0710", origin: "调教咖啡厅" },
  { name: "日向夏帆", bday: "0812", origin: "调教咖啡厅" },
  { name: "星川麻冬", bday: "1223", origin: "调教咖啡厅" },
  { name: "里中千惠", bday: "0101", origin: "房东妹子青春期" },
  { name: "本场切绘", bday: "0315", origin: "干物妹！小埋" },
  { name: "土间大平", bday: "0602", origin: "干物妹！小埋" },
  { name: "土间埋", bday: "0926", origin: "干物妹！小埋" },
  { name: "海老名菜菜", bday: "1019", origin: "干物妹！小埋" },
  { name: "橘·希尔芬福特", bday: "1224", origin: "干物妹！小埋" },
  { name: "后藤一里", bday: "0221", origin: "孤独摇滚！" },
  { name: "喜多郁代", bday: "0421", origin: "孤独摇滚！" },
  { name: "伊地知虹夏", bday: "0529", origin: "孤独摇滚！" },
  { name: "大槻悠悠子", bday: "0602", origin: "孤独摇滚！" },
  { name: "山田凉", bday: "0918", origin: "孤独摇滚！" },
  { name: "广井菊里", bday: "0928", origin: "孤独摇滚！" },
  { name: "伊地知星歌", bday: "1224", origin: "孤独摇滚！" },
  { name: "前原圭一", bday: "0413", origin: "寒蝉鸣泣之时" },
  { name: "龙宫礼奈", bday: "0728", origin: "寒蝉鸣泣之时" },
  { name: "园崎魅音", bday: "0710", origin: "寒蝉鸣泣之时" },
  { name: "北条沙都子", bday: "0624", origin: "寒蝉鸣泣之时" },
  { name: "古手梨花", bday: "0821", origin: "寒蝉鸣泣之时" },
  { name: "园崎诗音", bday: "0710", origin: "寒蝉鸣泣之时" },
  { name: "羽入", bday: "0801", origin: "寒蝉鸣泣之时" },
  { name: "知惠留美子", bday: "0503", origin: "寒蝉鸣泣之时" },
  { name: "大石藏人", bday: "1115", origin: "寒蝉鸣泣之时" },
  { name: "富竹次郎", bday: "0914", origin: "寒蝉鸣泣之时" },
  { name: "鹰野三四", bday: "0620", origin: "寒蝉鸣泣之时" },
  { name: "入江京介", bday: "1203", origin: "寒蝉鸣泣之时" },
  { name: "北条铁平", bday: "0528", origin: "寒蝉鸣泣之时" },
  { name: "赤坂卫", bday: "0803", origin: "寒蝉鸣泣之时" },
  { name: "北条悟史", bday: "0616", origin: "寒蝉鸣泣之时" },
  { name: "葛西辰由", bday: "1223", origin: "寒蝉鸣泣之时" },
  { name: "大宫忍", bday: "0606", origin: "黄金拼图" },
  { name: "爱丽丝·卡塔雷特", bday: "0405", origin: "黄金拼图" },
  { name: "小路绫", bday: "0915", origin: "黄金拼图" },
  { name: "猪熊阳子", bday: "0820", origin: "黄金拼图" },
  { name: "九条可怜", bday: "1201", origin: "黄金拼图" },
  { name: "栗山未来", bday: "0331", origin: "境界的彼方" },
  { name: "神原秋人", bday: "1007", origin: "境界的彼方" },
  { name: "名濑美月", bday: "1101", origin: "境界的彼方" },
  { name: "名濑博臣", bday: "0721", origin: "境界的彼方" },
  { name: "新堂爱", bday: "0825", origin: "境界的彼方" },
  { name: "新堂彩华", bday: "0522", origin: "境界的彼方" },
  { name: "二之宫雫", bday: "0618", origin: "境界的彼方" },
  { name: "伊波樱", bday: "0429", origin: "境界的彼方" },
  { name: "藤真弥勒", bday: "0108", origin: "境界的彼方" },
  { name: "名濑泉", bday: "0407", origin: "境界的彼方" },
  { name: "神原弥生", bday: "0313", origin: "境界的彼方" },
  { name: "森野真理", bday: "0219", origin: "恋爱小行星" },
  { name: "真中苍", bday: "0525", origin: "恋爱小行星" },
  { name: "木之幡米拉", bday: "0613", origin: "恋爱小行星" },
  { name: "樱井美景", bday: "0720", origin: "恋爱小行星" },
  { name: "猪濑舞", bday: "0912", origin: "恋爱小行星" },
  { name: "远藤幸", bday: "0810", origin: "恋爱小行星" },
  { name: "宇佐美绫乃", bday: "0412", origin: "恋爱小行星" },
  { name: "樱井千景", bday: "0510", origin: "恋爱小行星" },
  { name: "伊部小百合", bday: "1111", origin: "恋爱小行星" },
  { name: "七海悠", bday: "0102", origin: "恋爱小行星" },
  { name: "木之幡米莎", bday: "1202", origin: "恋爱小行星" },
  { name: "铃矢芽", bday: "0314", origin: "恋爱小行星" },
  { name: "铃矢萌", bday: "1002", origin: "恋爱小行星" },
  { name: "宗像草太", bday: "0224", origin: "铃芽之旅" },
  { name: "岩户铃芽", bday: "0524", origin: "铃芽之旅" },
  { name: "九头龙八一", bday: "0801", origin: "龙王的工作！" },
  { name: "水越澪", bday: "0824", origin: "龙王的工作！" },
  { name: "空银子", bday: "0909", origin: "龙王的工作！" },
  { name: "雏鹤爱", bday: "1007", origin: "龙王的工作！" },
  { name: "贞任绫乃", bday: "1203", origin: "龙王的工作！" },
  { name: "夜叉神天衣", bday: "1210", origin: "龙王的工作！" },
  { name: "明日花绪", bday: "0216", origin: "明日同学的水手服" },
  { name: "木崎江利花", bday: "0323", origin: "明日同学的水手服" },
  { name: "明日小路", bday: "0404", origin: "明日同学的水手服" },
  { name: "平岩萤", bday: "1007", origin: "明日同学的水手服" },
  { name: "冈部伦太郎", bday: "1214", origin: "命运石之门" },
  { name: "椎名真由理", bday: "0201", origin: "命运石之门" },
  { name: "桥田至", bday: "0519", origin: "命运石之门" },
  { name: "牧濑红莉栖", bday: "0725", origin: "命运石之门" },
  { name: "桐生萌郁", bday: "0606", origin: "命运石之门" },
  { name: "漆原琉华", bday: "0830", origin: "命运石之门" },
  { name: "秋叶留未穗", bday: "0403", origin: "命运石之门" },
  { name: "阿万音铃羽", bday: "0927", origin: "命运石之门" },
  { name: "比屋定真帆", bday: "1102", origin: "命运石之门" },
  { name: "椎名篝", bday: "0707", origin: "命运石之门" },
  { name: "阿万音由季", bday: "0531", origin: "命运石之门" },
  { name: "天王寺裕吾", bday: "0312", origin: "命运石之门" },
  { name: "中濑克美", bday: "0114", origin: "命运石之门" },
  { name: "来岛枫", bday: "1004", origin: "命运石之门" },
  { name: "环彩羽", bday: "0822", origin: "魔法纪录 魔法少女小圆外传" },
  { name: "朝雾彩", bday: "0408", origin: "魔法少女网站" },
  { name: "穴泽虹海", bday: "0705", origin: "魔法少女网站" },
  { name: "奴村露乃", bday: "0409", origin: "魔法少女网站" },
  { name: "雨谷小雨", bday: "1106", origin: "魔法少女网站" },
  { name: "水莲寺清春", bday: "1112", origin: "魔法少女网站" },
  { name: "潮井梨奈", bday: "1208", origin: "魔法少女网站" },
  { name: "雫芽纱理奈", bday: "0425", origin: "魔法少女网站" },
  { name: "鹿目圆", bday: "1003", origin: "魔法少女小圆" },
  { name: "琪琪", bday: "0202", origin: "魔女宅急便" },
  { name: "一之濑双叶", bday: "0825", origin: "那就是声优！" },
  { name: "萌咲莓", bday: "0505", origin: "那就是声优！" },
  { name: "小花铃", bday: "0317", origin: "那就是声优！" },
  { name: "立花泷", bday: "1201", origin: "你的名字。" },
  { name: "宫水三叶", bday: "1201", origin: "你的名字。" },
  { name: "海凪日和", bday: "0104", origin: "女孩的钓鱼慢活" },
  { name: "吉永恋", bday: "0630", origin: "女孩的钓鱼慢活" },
  { name: "海凪小春", bday: "1115", origin: "女孩的钓鱼慢活" },
  { name: "大户爱", bday: "0615", origin: "奇蛋物语" },
  { name: "风衣叶冬优", bday: "0124", origin: "请问您今天要来点兔子吗？" },
  { name: "天天座理世", bday: "0214", origin: "请问您今天要来点兔子吗？" },
  { name: "保登摩卡", bday: "0313", origin: "请问您今天要来点兔子吗？" },
  { name: "保登心爱", bday: "0410", origin: "请问您今天要来点兔子吗？" },
  { name: "桐间纱路", bday: "0715", origin: "请问您今天要来点兔子吗？" },
  { name: "条河麻耶", bday: "0808", origin: "请问您今天要来点兔子吗？" },
  { name: "宇治松千夜", bday: "0919", origin: "请问您今天要来点兔子吗？" },
  { name: "青山Blue Mountain", bday: "1027", origin: "请问您今天要来点兔子吗？" },
  { name: "奈津惠", bday: "1102", origin: "请问您今天要来点兔子吗？" },
  { name: "香风智乃", bday: "1204", origin: "请问您今天要来点兔子吗？" },
  { name: "羽岛伊月", bday: "0606", origin: "如果有妹妹就好了。" },
  { name: "羽岛千寻", bday: "0906", origin: "如果有妹妹就好了。" },
  { name: "石田将也", bday: "0208", origin: "声之形" },
  { name: "西宫硝子", bday: "0607", origin: "声之形" },
  { name: "池谷乃乃", bday: "0201", origin: "斯特拉的魔法" },
  { name: "藤川歌夜", bday: "0402", origin: "斯特拉的魔法" },
  { name: "饭野水叶", bday: "0509", origin: "斯特拉的魔法" },
  { name: "关菖蒲", bday: "0723", origin: "斯特拉的魔法" },
  { name: "本田珠辉", bday: "0828", origin: "斯特拉的魔法" },
  { name: "布田裕美音", bday: "0914", origin: "斯特拉的魔法" },
  { name: "百武照", bday: "1222", origin: "斯特拉的魔法" },
  { name: "村上椎奈", bday: "1225", origin: "斯特拉的魔法" },
  { name: "天野阳菜", bday: "0822", origin: "天气之子" },
  { name: "种村小依", bday: "0220", origin: "天使降临到了我身边！" },
  { name: "小之森夏音", bday: "0228", origin: "天使降临到了我身边！" },
  { name: "白咲花", bday: "0307", origin: "天使降临到了我身边！" },
  { name: "星野日向", bday: "0510", origin: "天使降临到了我身边！" },
  { name: "星野宫子", bday: "0909", origin: "天使降临到了我身边！" },
  { name: "姬坂乃爱", bday: "1124", origin: "天使降临到了我身边！" },
  { name: "诺艾尔", bday: "1103", origin: "天体的秩序" },
  { name: "高坂桐乃", bday: "0408", origin: "我的妹妹哪有这么可爱！" },
  { name: "五更琉璃", bday: "0420", origin: "我的妹妹哪有这么可爱！" },
  { name: "新垣绫濑", bday: "0502", origin: "我的妹妹哪有这么可爱！" },
  { name: "田村麻奈实", bday: "0504", origin: "我的妹妹哪有这么可爱！" },
  { name: "斋藤枫", bday: "0116", origin: "向山进发" },
  { name: "雪村葵", bday: "0219", origin: "向山进发" },
  { name: "千手院小春", bday: "0518", origin: "向山进发" },
  { name: "黑崎穗香", bday: "0625", origin: "向山进发" },
  { name: "青羽心夏", bday: "0811", origin: "向山进发" },
  { name: "仓上日向", bday: "1111", origin: "向山进发" },
  { name: "小林", bday: "0423", origin: "小林家的龙女仆" },
  { name: "才川乔吉", bday: "0510", origin: "小林家的龙女仆" },
  { name: "才川莉子", bday: "0821", origin: "小林家的龙女仆" },
  { name: "真土翔太", bday: "1222", origin: "小林家的龙女仆" },
  { name: "雷门瞬", bday: "0409", origin: "星灵感应" },
  { name: "宝木遥乃", bday: "1018", origin: "星灵感应" },
  { name: "小之星海果", bday: "0122", origin: "星灵感应" },
  { name: "椎名", bday: "0217", origin: "幸腹涂鸦" },
  { name: "町子凉", bday: "0622", origin: "幸腹涂鸦" },
  { name: "森野麒麟", bday: "1219", origin: "幸腹涂鸦" },
  { name: "佐仓慈", bday: "0310", origin: "学园孤岛" },
  { name: "丈枪由纪", bday: "0405", origin: "学园孤岛" },
  { name: "惠飞须泽胡桃", bday: "0807", origin: "学园孤岛" },
  { name: "若狭悠里", bday: "1011", origin: "学园孤岛" },
  { name: "直树美纪", bday: "1210", origin: "学园孤岛" },
  { name: "赤座灯里", bday: "0724", origin: "摇曳百合" },
  { name: "岁纳京子", bday: "0328", origin: "摇曳百合" },
  { name: "船见结衣", bday: "0422", origin: "摇曳百合" },
  { name: "吉川千夏", bday: "1106", origin: "摇曳百合" },
  { name: "杉浦绫乃", bday: "0120", origin: "摇曳百合" },
  { name: "池田千岁", bday: "0310", origin: "摇曳百合" },
  { name: "大室樱子", bday: "0907", origin: "摇曳百合" },
  { name: "古谷向日葵", bday: "0616", origin: "摇曳百合" },
  { name: "松本理世", bday: "0523", origin: "摇曳百合" },
  { name: "西垣奈奈", bday: "0621", origin: "摇曳百合" },
  { name: "池田千鹤", bday: "0310", origin: "摇曳百合" },
  { name: "船见真理", bday: "0830", origin: "摇曳百合" },
  { name: "古谷枫", bday: "1030", origin: "摇曳百合" },
  { name: "大室抚子", bday: "0121", origin: "摇曳百合" },
  { name: "大室花子", bday: "0807", origin: "摇曳百合" },
  { name: "吉川友子", bday: "0216", origin: "摇曳百合" },
  { name: "赤座茜", bday: "1213", origin: "摇曳百合" },
  { name: "志摩凛", bday: "1001", origin: "摇曳露营△" },
  { name: "各务原抚子", bday: "0304", origin: "摇曳露营△" },
  { name: "犬山葵", bday: "0304", origin: "摇曳露营△" },
  { name: "大垣千明", bday: "0831", origin: "摇曳露营△" },
  { name: "齐藤惠那", bday: "0901", origin: "摇曳露营△" },
  { name: "御庭摘希", bday: "0111", origin: "一起一起这里那里" },
  { name: "戌井榊", bday: "0414", origin: "一起一起这里那里" },
  { name: "春野姬", bday: "0512", origin: "一起一起这里那里" },
  { name: "片濑真宵", bday: "0910", origin: "一起一起这里那里" },
  { name: "音无伊御", bday: "1015", origin: "一起一起这里那里" },
  { name: "乔伊·莫奇马兹", bday: "0303", origin: "玉子市场" },
  { name: "朝雾史织", bday: "0402", origin: "玉子市场" },
  { name: "梅查·莫奇马兹", bday: "0406", origin: "玉子市场" },
  { name: "北白川馅子", bday: "0504", origin: "玉子市场" },
  { name: "牧野神奈", bday: "0607", origin: "玉子市场" },
  { name: "常盘绿", bday: "0819", origin: "玉子市场" },
  { name: "大路饼藏", bday: "1010", origin: "玉子市场" },
  { name: "北白川玉子", bday: "1231", origin: "玉子市场" },
  { name: "春日野悠", bday: "0205", origin: "缘之空" },
  { name: "春日野穹", bday: "0205", origin: "缘之空" },
  { name: "仓永梢", bday: "0601", origin: "缘之空" },
  { name: "渚一叶", bday: "0803", origin: "缘之空" },
  { name: "天女目瑛", bday: "0803", origin: "缘之空" },
  { name: "依媛奈绪", bday: "1007", origin: "缘之空" },
  { name: "桐生慧辉", bday: "1011", origin: "只要长得可爱即使是变态你也喜欢吗？" },
  { name: "桐生瑞叶", bday: "0303", origin: "只要长得可爱即使是变态你也喜欢吗？" },
  { name: "雏月加代", bday: "0302", origin: "只有我不存在的城市" },
  { name: "藤沼悟", bday: "0302", origin: "只有我不存在的城市" },
  { name: "小鸟游十花", bday: "0215", origin: "中二病也要谈恋爱！" },
  { name: "小鸟游六花", bday: "0612", origin: "中二病也要谈恋爱！" },
  { name: "七宫智音", bday: "0706", origin: "中二病也要谈恋爱！" },
  { name: "富㭴勇太", bday: "0707", origin: "中二病也要谈恋爱！" },
  { name: "凸守早苗", bday: "0809", origin: "中二病也要谈恋爱！" },
  { name: "丹生谷森夏", bday: "0830", origin: "中二病也要谈恋爱！" },
  { name: "五月七日茴香", bday: "1014", origin: "中二病也要谈恋爱！" },
  { name: "一色诚", bday: "1207", origin: "中二病也要谈恋爱！" },
  { name: "神前美月", bday: "1221", origin: "最近，妹妹的样子有点怪。" },
];

var today = new Date();
var month = today.getMonth() + 1;
var day = today.getDate();
if (month < 10) {
  month = "0" + month;
}
if (day < 10) {
  day = "0" + day;
}
var date = month + day;

var result = [];
for (var i = 0; i < list.length; i++) {
  var item = list[i];
  if (item.bday == date) {
    result.push(item);
  }
}

if (result.length == 0) {
  document.getElementById("result").innerHTML = "今天没有角色生日...";
} else {
  var output = "";
  for (var j = 0; j < result.length; j++) {
    var role = result[j];
    output += role.name + " [" + role.origin + "]" + "<br>";
  }
  document.getElementById("result").innerHTML = output;
}